### ISSUE TITLE
misc_getApplyFunc: does not return correct apply function

### ISSUE THREAD

**Issue by MihailBogojeski** [bbci/bbci_public#103]
If the training function is named train_Fcn, misc_getApplyFunc takes the full name and appends apply to it, so it will search for apply_train_Fcn and after not finding it will return apply_separatingHyperplane as the apply function. The function works as expected if the training function is named without the 'train_' prefix.

**Comment by BenjaminBlankertz** [comment]
Thanks for reporting this problem. I fixed the bug in misc_getApplyFunc.
