### ISSUE TITLE
mrk_defineClasses has problems with cell type event descriptions in Matlab2014a

### ISSUE THREAD

**Issue by DanielMiklody** [bbci/bbci_public#107]
in Matlab2014a (and probably others) the function markers/mrk_defineClass changes the type of mk.event.desc into a struct in the line 
_mrk= struct('time', mk.time, 'event',struct('desc',mk.event.desc));_

For me, this causes errors in later handling of the data.

My solution is simply the following code instead, but I don't oversee the whole purposes of this function and don't know if this doesn't cause it to malfunction it other contexts...

_mrk= struct('time', mk.time, 'event',mk.event);_

**Comment by BenjaminBlankertz** [comment]
Hopefully solved. Daniel will commit.
