### ISSUE TITLE
Demo for validation of classification including feature selection

### ISSUE THREAD

**Issue by BenjaminBlankertz** [bbci/bbci_public#11]
If the classification method includes feature selection, that has to be performed on the training set only. In the old svn toolbox, there is a demo that first shows the wrong validation (feature selection on the whole data set) which underestimates the generalization error. In a second part, the valid validation is demonstrated. That should be transferred to the new git toolbox. Please use some of the demo datasets (see other demos).

**Comment by MarkusWenzel** [comment]
I am working on it.
