### ISSUE TITLE
Determine range in plot_scalpEvolutionPlusChannel beforehand

### ISSUE THREAD

**Issue by BenjaminBlankertz** [bbci/bbci_public#13]
In the typical use case the scalps plotted in plot_scalpEvolutionPlusChannel have a common range (option UnifyCLim set to 'global', I think). Currently, it is implemented such that each scalp is plotted individually with its own range and in the end all CLims are unified. That work well EXCEPT that the contour lines might have different spacings in each map, because that is not modified when CLim is changed. Therefore the function must be implemented such that the range of all maps is determined beforehand, and the individual maps are plotted directly with that global range.

**Comment by i-sturm** [comment]
I'll take that.
