### ISSUE TITLE
Wrapper functions trainClassifier and applyClassifier are buggy and not documented at all

### ISSUE THREAD

**Issue by mattskraft** [bbci/bbci_public#135]

**Comment by BenjaminBlankertz** [comment]
In what situation are those functions buggy? Please describe, otherwise it's hard to work on the issue.

**Comment by mattskraft** [comment]
Sorry, that was too imprecise. In the function applyClassifier the second argument 'model' is expected but not used at all.

**Comment by BenjaminBlankertz** [comment]
Ok, thanks. I removed the obsolete input argument from applyClassifier and added help text. Please let me know if there are further issues.
