### ISSUE TITLE
Add a demo for multiand spatial filtering and subsequent feature combination

### ISSUE THREAD

**Issue by svendaehne** [bbci/bbci_public#143]
A demo would be nice that shows how to use our functions to implement a multiband spatial filtering approach (CSP or SPoC) with subsequent combination of bandpower features (via LDA or regression) and all of that in a crossvalidation setting. 
The functions for all of the above are already there. However, a script that showcases how to use them is needed.

**Comment by DanielMiklody** [comment]
I claim
