### ISSUE TITLE
Online bbci_apply crashes when markers come as cell arrays

### ISSUE THREAD

**Issue by janfb** [bbci/bbci_public#151]
In **bbci_apply_initData** the initial _marker.desc_ is set to struct by default. So is the _bbci.quit_condition.marker_ in **bbci_apply_setdefaults**. The LSL marker stream returns a cell array. As a consequence bbci_apply_queryMarker crashes when comparing struct and cell in line 41. Any suggestions?

**Comment by BenjaminBlankertz** [comment]
Please try

> > dbstop in bbci_apply_acquireData at 64
> > and rerun. In your case, mrkDesc should be a cell here (because your acquire function returns markers as cell) and then maker.desc should be initialized as cell array. Please check what goes wrong here.

Btw: I don't understand what you mean by saying 'marker.desc' is set to struct. It is defined as [].

**Comment by janfb** [comment]
I think there are two things that go wrong here. 
1)

> in bbci_apply_setDefaults line 292 we set `bbci.quit_condition.marker=[]` by default, irrespective of the acquire function. This causes bbci_apply_queryMarker to throw an error when comparing [] and {} in line 41.

2) independent from 1): 

> the initialization of mrkDesc to the marker format of the current acquisition fct ([] or {}) depends on the occurrence of a marker because it is inside of `if nNewMarkers>0´: If there is no marker in the first data block then marker.desc will not be changed to {} and again there will be an error in bbci_apply_queryMarker line 41. 

Solution: 

> I prevented the errors by adding an if-else block in bbci_apply_setDefaults line 292, that sets bbci.quit_condition.marker to {} if the acquisition fct is _lsl and to [] otherwise. Then one can solve the second problem by initializing `data.marker.desc = bbci.quit_condition.marker` in bbci_apply_initData line 23. 

A different solution would be to add an general option for `bbci.marker_format` or to change the output of the bbci_acquire_lsl. Do you agree?

**Comment by BenjaminBlankertz** [comment]
Would changing line 40 of bbci_apply_queryMarker to
  if nargin > 2 && ~isempty(idx)
also solve the problem? Then I would prefer that.

**Comment by janfb** [comment]
It solves the 2) problem. But 1) still throws an error because `bbci.quit_condition.marker=[]`so that line 41 tries `ismember({'marker'}, ['quit_marker'], 'legacy')`, which does not work. 
We somehow have to make the `bbci.quit_condition.marker` sensitive to the marker format.

**Comment by BenjaminBlankertz** [comment]
Ok, you need to change line 40 of bbci_apply_queryMarker to
if nargin > 2 && ~isempty(idx) && ~isempty(mrkDesc),

**Comment by janfb** [comment]
OK this works only if we then add `|| isempty(mrkDesc)` in line 45. Otherwise, `marker_out` will not be empty because `idx` is not empty, which causes acquisition to stop.

**Comment by BenjaminBlankertz** [comment]
Ok, thanks. Since I did not see a pull request from you, I commit your 
suggested fix and pushed it.

I thought that it might be even better to insert at the very beginning 
of the function

if isempty(mrkDesc),
   marker_out= [];
   return
end

instead of add the condition at two places. Do you agree?

**Comment by janfb** [comment]
Yes, sounds good.

**Comment by janfb** [comment]
I added it to my local fork and pushed it. If you merge the pull request #139 it should be included.
