### ISSUE TITLE
bbci_apply_sendControl.m to "Processing"

### ISSUE THREAD

**Issue by MarkusWenzel** [bbci/bbci_public#153]
Test if bbci_apply_sendControl.m can connect via UDP to the visualization software "Processing".

**Comment by BenjaminBlankertz** [comment]
BBCI Feedback with processing was done for the BBCI Spraying Game. The communication works simply with the provided UDP interface:
  bbci.feedback.receiver= 'udp';
see also the run script in (the non-public folder):
  bbci_private/acquisition/scripts/teaching/2014ss-BCIPJ-Team2
Receiving the signals in processing is also very simple, see BCIListenForClassifier.pde in
  bbci_private/feedbacks/processing/SprayYourBBCIFeedback
As far was I remember, you need to install the hypermedia package manually.
