### ISSUE TITLE
winthreads.h not found for compilation to mex-file

### ISSUE THREAD

**Issue by MonikaHeringhaus** [bbci/bbci_public#154]
For online acquisition, make_bbci_acquire_bv.m is used to create the mex-file. 
In bbci_acquire_bv.cpp and brainserver.c the file winthreads.h is included.

Where can this header file be found? 

I've tried to use winpthreads.h by Lockless Inc instead but without success. This only causes a whole new series of errors in Matlab.

**Comment by BenjaminBlankertz** [comment]
Which windows version do you use?

**Comment by MonikaHeringhaus** [comment]
Win 8.1 (64 bit)

**Comment by BenjaminBlankertz** [comment]
I currently do not have access to a computer with Window 8 and a C-compiler installed. I will fix this issue later. For now, I will send you the winthread files by mail.
