### ISSUE TITLE
Question: How setting method or examples for bbci online with customized function ?

### ISSUE THREAD

**Issue by tigoum** [bbci/bbci_public#155]
Dear bbci researcher.

My name is Ahn Min-Hee, I am member on mindbrain lab on korea university, in seoul, south korea.

We research & development BMI that is constructed 32 channel EEG of brainproduct co. & customized
robot. We tried implementation for BMI code using bbci_public/online.

First, we search & find a bbci online demo: demo_bbcionline_matlab_feedback.m
Second, we modified its code for our requirement: data acquisition from brain vision recorder,
  using our own feature/classification method, and process by our own feedback receiver.

Then, we are hold this work, because we don't know coding or parameter setting methods that
connect with our feature/classification function & our feedback receiver to bbci struct...

We want the calculation using our feature/classification function(and FFT) during every 4 seconds.
(of course, realtime data is received from brain vision recorder. It is successes with above demo)
And receive its result on our feedback receiver.

What shall we does? 
Would you send us with some more hint or examples?

Thank you very much.

Best,

tigoum

**Comment by BenjaminBlankertz** [comment]
Dear Ahn Min-Hee,
sorry for the late response. Our toolbox programming day had to be postponed.
- "We want the calculation using our feature/classification function(and FFT) during every 4 seconds.
  [...] And receive its result on our feedback receiver."
  -> A classifier output is generated each time a new data package is received. If you want features and classifier output calculated every 4 seconds, you should set
  `bbci.source.min_blocklength= 4*1000;`
- "we don't know coding or parameter setting methods that connect with our feature/classification function & our feedback receiver to bbci struct..."
  -> I am not sure what the question is. What kind of feedback would you like to use? (If you generate classifier outputs only every 4s, the continuous cursor control from the demo_bbcionline_matlab_feedback is not appropriate.
  -> For testing, you could leave the bbci.feedback empty and just let the output of the classifier be printed on the screen (is bbci.feedback is empty, logging to the screen is done by default).
