### ISSUE TITLE
acq_checkTriggers

### ISSUE THREAD

**Issue by MarkusWenzel** [bbci/bbci_public#158]
acq_checkTriggers complains even though all triggers are sent correctly (as displayed in the monitor of the brain vision recorder and if the function is manually evaluated line by line).

Here is a typical output:

sending trigger:   1 -> received: nothing.
sending trigger:   2 -> received:   1.
sending trigger:   4 -> received: nothing.
sending trigger:   8 -> received:   4.
sending trigger:  16 -> received:   8.
sending trigger:  32 -> received:  16.
sending trigger:  64 -> received:  32.
sending trigger: 128 -> received:  64.
Error using acq_checkTriggers (line 37)
!!! Trigger test unsuccessful !!!\n

**Comment by BenjaminBlankertz** [comment]
Maybe this does not below here, as it could also be a problem in the setup, not necessarily in the toolbox. You say that the triggers are correctly _received_ (i.e. shown) in the BV recorder? What happens if you save the data - are the correct trigger 1, 2, 4, ..., 128 in the file?

**Comment by BenjaminBlankertz** [comment]
Problem occurred due to a too short time value that had sneaked into the function in a previous change. Now everything is back operational.
