### ISSUE TITLE
file_readBV

### ISSUE THREAD

**Issue by stephaniebrandl** [bbci/bbci_public#159]
there maybe a bug in the file_readBV function regarding the low-pass filtering
when we recently loaded ERP Spelling data with the following code (same as in the demo)
% low-pass filter
  Wps = [42 49]/hdr.fs*2;
  [n, Ws] = cheb2ord(Wps(1), Wps(2), 3, 40);
  [filt.b, filt.a]= cheby2(n, 50, Ws);
  % load raw data, downsampling is done while loading (after filtering)
  [cnt, mrk_orig] = file_readBV(file, 'Fs',Fs, 'Filt',filt);

we got different (and weird) power spectra compared to first read the data and low-pass filter afterwards
[cnt, mrk_orig] = file_readBV('CenterSpellerCalibration');
mrk = mrk_defineClasses(mrk_orig, {[30:49],[10:29]; 'target','non-target'});
% low-pass filter
Wps = [42 49]/hdr.fs*2;
[n, Ws] = cheb2ord(Wps(1), Wps(2), 3, 40);
[filt.b, filt.a]= cheby2(n, 50, Ws);
cnt= proc_filtfilt(cnt, filt.b, filt.a);

unfortunately I didn't have the time to check that problem and I won't be at TU for the next heckathon but I think it is important to check if that problem also appears for other data.

**Comment by DanielMiklody** [comment]
Hey I looked into this as well:
Difference 1: filtering with file_readBV only implements something in c similar to the proc_filt function not proc_filtfilt. WIthout downsampling I get practically the same results (just some numerically caused minor deviations).
Difference 2: The downsampling. If I load filter (proc_filt) and downsample (proc_resample) within the toolbox, I get similar but slightly more different results.
[Large scale](https://owncloud.tu-berlin.de/index.php/s/PGa4jq9CYcNYExH)
[Small scale](https://owncloud.tu-berlin.de/index.php/s/GZ3Fv9XJnJsnLba)
[Mini scale](https://owncloud.tu-berlin.de/index.php/s/2TGqGdmRm2mGe5O)

So far my investigations. I think the differences are minor resampling artifacts and actually the file_readBV looks better to me (less oscilating).

**Comment by BenjaminBlankertz** [comment]
Same for Markus and me. We did not find substantial differences. Please check again, and tell us in which dataset you observe the problem. Thank you.

**Comment by DanielMiklody** [comment]
maybe the hdr.fs used was not corresponding to the data sampling frequency (I can't see from the code, how it was loaded)..
