### ISSUE TITLE
Implement proc_csp

### ISSUE THREAD

**Issue by mattskraft** [bbci/bbci_public#160]
The current proc_cspAuto is overloaded with unnecessary functionalities and the parsing of input arguments does not work properly under certain circumstances.
I suggest to distill the core functionalities from proc_cspAuto and implement a new nice and clean proc_csp that actually does what it is supposed to.

**Comment by svendaehne** [comment]
I think we're done with this one. I suggest we close it and open a new issue right away for writing some example scripts for it ;-)
