### ISSUE TITLE
BUG: proc_appendEpochs

### ISSUE THREAD

**Issue by mattskraft** [bbci/bbci_public#17]
proc_appendEpochs > (proc_rValues) > proc_meanAcrossTime:
proc_appendEpochs (used e.g. by proc_rValues) concatenates the time vector in field .t along a third dimension for each appended epoch. is that necessary? the problem: proc_meanAcrossTime doesn't work on the resulting data structure because it assumes a 1 x nT dimensional .t

**Comment by BenjaminBlankertz** [comment]
This bug was fixed.
