### ISSUE TITLE
Question: Epoch averaging 

### ISSUE THREAD

**Issue by okbalefthanded** [bbci/bbci_public#199]
Hi,

following the ERPs classification demo and checking the number of epochs used for the stratified 10-fold cross-validation I assume that the training and testing is done on the basis of single-trial i.e. only 1 repetition for each stimulus is taken.

My question is, how epoch averaging is implemented (if it's already programmed) in the toolbox ?

**Comment by BenjaminBlankertz** [comment]
I would suggest not to average the ERPs, but to use single-trials for classification. The averaging can rather be done afterwards on the classifier output. (However, the difference in performance between averaging epochs and averaging classifier outputs is not large.)
Averaging classifier outputs is not implemented in the public toolbox for validation. It is just implemented in the online system (function bbci_control_ERPSpeller.m).

**Comment by okbalefthanded** [comment]
Thanks for the reply and suggestion.
