### ISSUE TITLE
reordering in proc_selectChannels [Johannes]

### ISSUE THREAD

**Issue by JohannesHoehne** [bbci/bbci_public#20]
proc_selectChannels  returns an epo or cnt with an ordered list  of channes. So if I ask for 

cnt2 = proc_selectChannels(cnt1, {'Fz', 'Oz', 'Cz'});
then 
cnt2.clab -->  {'Fz', 'Cz', 'Oz'}

There should be a warning at least!!!

**Comment by BenjaminBlankertz** [comment]
Fixing this one, will (probably) also fix issue #8.

**Comment by JohannesHoehne** [comment]
I'm working on it
