### ISSUE TITLE
What is TIMEEPS?

### ISSUE THREAD

**Issue by damo-da** [bbci/bbci_public#213]
It seems that the sole purpose of `TIMEEPS` used in `proc_segmentation.m` [L#108](https://github.com/bbci/bbci_public/blob/master/processing/proc_segmentation.m#L108) is to increment a frame. I am unable to understand why.

**Comment by BenjaminBlankertz** [comment]
Hi underscoredam,
for some reason, I didn't receive notifications about issues for several months, and so I also missed your question. I am sorry about that.
Unfortunately, I don't remember the reason exactly. In the straight forward implementation, numerical errors could lead to an unexpected shift in the extracted segments, when the sampling interval (1000/cnt.fs) was fractional. Introducing the TIMEEPS code, this shift is avoided. For integer sampling intervals it should not make a difference.
Best regards,
  Benjamin
