### ISSUE TITLE
Supported Matlab versions

### ISSUE THREAD

**Issue by jsosulski** [bbci/bbci_public#214]
On the page [ToolboxRequirements](https://github.com/bbci/bbci_public/blob/master/doc/ToolboxRequirements.markdown) it states that Matlab versions later than 2007 are supported.
I tried updating my Matlab installation from 2014b to 2018b and found that at least one function does no longer work ([`misc_checkType`](https://github.com/bbci/bbci_public/blob/d6bf0e442d58d7a6f04952660712b617377b425e/misc/misc_checkType.m#L106)) as the Matlab function `inputname` seems to return other outputs than in Matlab 2014b.

As I would guess that checking the whole code for compatibility is a tedious task, it would be easier to just state that Matlab up to 2014b is compatible (or whichever latest version is known to work).

**Comment by BenjaminBlankertz** [comment]
Everything was fine until Matlab 2018a, the version I had on my laptop. Matlab does not care about downwards compatibility, which is a pain for maintaining toolboxes. I fixed the issue with a hack (should be revisited for a nicer solution). Now the demos run again with Matlab 2019a.
Sorry for the inconvenience.
