### ISSUE TITLE
Introduce 'markers' for longer blocks

### ISSUE THREAD

**Issue by BenjaminBlankertz** [bbci/bbci_public#26]
For specifying longer intervals, e.g., blocks of conditions 'low workload', 'high workload'. These blocks may have different lengths. Then there should be functions like mrk_evenlyWithinBlocks that outputs a regular marker structure, with e.g., one marker every 1000ms within the given blocks with corresponding marker labels.
There were some functions (I think called blk_\* in the old SVN toolbox). Not sure whether that was the best way to do it, but it is at least a reference.

**Comment by phoebe28** [comment]
I already started to modify the functions mrk_evenlyWithinBlocks and connected ones, to work on the relax files in the new git, i can have a look if i can solve this issue.
Laura

**Comment by phoebe28** [comment]
It will take longer time, but i am working on it.
Laura
