### ISSUE TITLE
util_printFigure: printing to PDF

### ISSUE THREAD

**Issue by BenjaminBlankertz** [bbci/bbci_public#27]
Currently util_printFigure uses a hack to produce PDFs: print to EPS first and then call a console scirpt to convert EPS to PDF (works under Linux only). But there seems to be the possibility to print directly to PDF with option -dpdf in Matlab's print function. Probably, this feature was introduced at some new Matlab version: Change util_printFigure to check the Matlab version and use the -dpdf option if available.

**Comment by i-sturm** [comment]
I'll take this.

**Comment by DanielMiklody** [comment]
I think this claim is obsolete! :)

**Comment by BenjaminBlankertz** [comment]
The Matlab -dpdf option gives a crappy output. A nice alternative would be to use export_fig
  https://github.com/altmany/export_fig.git
That takes quite a while to print a PDF with scalp maps, but the output is nice.
