### ISSUE TITLE
add help to plot_channel

### ISSUE THREAD

**Issue by BenjaminBlankertz** [bbci/bbci_public#29]
Currently, you have to look into the help of plotutil_channel1D resp 2D. But help should be available in plot_channel.

**Comment by IrinaNicolae** [comment]
I can take this.

**Comment by DanielMiklody** [comment]
the help of 1D has slightly changed due to new functionality... (no .plotStd anymore but .plotStat instead).. I have filed a pull request but it's not merged, yet.

**Comment by DanielMiklody** [comment]
OK, it is merged, now, the help in master is up to date
