### ISSUE TITLE
Remove outdated identifier strings

### ISSUE THREAD

**Issue by BenjaminBlankertz** [bbci/bbci_public#32]
like this one:
  $Id: percentiles.m,v 1.4 2006/08/30 14:21:27 neuro_toolbox Exp $
from the functions:
stat_percentiles.m
stat_normal_cdf
nansum.m
nanstd.m

**Comment by DanielMiklody** [comment]
I claim this, too.

**Comment by DanielMiklody** [comment]
fixed: please merge and close!
