### ISSUE TITLE
function to add percentiles

### ISSUE THREAD

**Issue by BenjaminBlankertz** [bbci/bbci_public#35]
Similar to adding STD or SEM, there should be the possibility to add certain percentiles to EPO data. Instead of overloading the proc_average function with more functionality, I suggest to create a new function that adds(classwise!) percentiles to EPO data. The percentiles can be calculated with stat_percentiles.
Make sure, that plot_channel is able to use the percentile information (e.g. plotting tubes from 25-percentile to 75-percentile around the mean), see issue #31.

**Comment by BenjaminBlankertz** [comment]
Daniel takes care of this one.

**Comment by DanielMiklody** [comment]
closed?!

**Comment by BenjaminBlankertz** [comment]
Thanks!
