### ISSUE TITLE
Fix layout in plot_scalpEvolution

### ISSUE THREAD

**Issue by BenjaminBlankertz** [bbci/bbci_public#37]
This function should use the whole axis for the scalp maps. However, it seems to reserve space for plotting additionally a channel (as ERP), which is left blank.
Try this:

> > demo_analysis_ERPs
> > fig_set(1, 'Resize',[1 1/2]); clf
> > plot_scalpEvolution(epo_r, mnt, ival_scalps)

**Comment by MarkusWenzel** [comment]
Claimed.
