### ISSUE TITLE
Typo on bbci.de/toolbox

### ISSUE THREAD

**Issue by MarkusWenzel** [bbci/bbci_public#38]
Change:  "bbci-tooblox" google group.
To: "bbci-toolbox" google group.
On the website: bbci.de/toolbox

**Comment by BenjaminBlankertz** [comment]
Please correct the respective file in bbci_public/doc. The webpages on bbci.de/toolbox will be generated by on those files. Basti is working on that.

**Comment by DanielMiklody** [comment]
I claim this!

**Comment by DanielMiklody** [comment]
fixed: please merge and close!
