### ISSUE TITLE
Solve problem with new graphic handles encounted in Matlab >= 2014b

### ISSUE THREAD

**Issue by BenjaminBlankertz** [bbci/bbci_public#39]
In the newest versions of Matlab, handles to graphic objects are new, specific types of variables, while before they have just been number. This makes problems in a number of ways (don't know exactly, because I have an old version of Matlab).

**Comment by phoebe28** [comment]
I modified the function bar_withAntenna.m, as soon as somebody finds another function with shows the same problems, please open a specific issue and i can have a look at it.+
Laura

**Comment by BenjaminBlankertz** [comment]
The problem with bar_withAntenna was a special one. There are still huge problems with basic plotting functions for newer versions of Matlab.

**Comment by BenjaminBlankertz** [comment]
I hope this solves all problems. If not, please reopen.
