### ISSUE TITLE
Add Matlab syntax highlighting to code examples in markdown files

### ISSUE THREAD

**Issue by venthur** [bbci/bbci_public#4]
Most markdown files in the `doc` directory come with code examples that use fenced code blocks:

``````
```
some code
some more code
```
``````

This signals markdown that there is code and it will format properly. But with a _little_ more effort we can tell markdown the programming language as well and get proper syntax highlighting:

``````
```Matlab
some code
some more code
```
``````

I fixed one file:

https://github.com/bbci/bbci_public/blob/master/doc/ToolboxOnlineBbciApplyIntroduction.markdown

Note that the first example uses Pseudocode, and the rest is Matlab. The others should be fixed as well.

**Comment by IrinaNicolae** [comment]
Are you working on this? If not, I can start fixing them.

**Comment by BenjaminBlankertz** [comment]
It's not taken yet. Please go ahead! Thanks!

Am 22.04.2015 um 12:44 schrieb IrinaNicolae:

**Comment by IrinaNicolae** [comment]
I think I didn't specified in the second commit the 'Closes' function. Can you close this issue, please? Thank you!
