### ISSUE TITLE
Obsolete property specified in demo_analysis_Spectra.m?

### ISSUE THREAD

**Issue by BenjaminBlankertz** [bbci/bbci_public#46]
In demo_analysis_Spectra.m

> H= grid_plot(spec, mnt, opt_grid_spec,'XUnit', spec.xUnit, 'YUnit', spec.yUnit);
> the spcification of units should be obsolete (default of grid_plot)? Please check and remove if that's true.

**Comment by DanielMiklody** [comment]
CLAIM

**Comment by DanielMiklody** [comment]
it was obsolete, verified, will commit the fix soon.
