### ISSUE TITLE
Provide toolbox wrappers for some ICA algos

### ISSUE THREAD

**Issue by svendaehne** [bbci/bbci_public#6]

**Comment by svendaehne** [comment]
For this issue (but also for the SSD/SPoC stuff) we need to decide how to include external functions, such as ICA implementations. 

SPM and Fieldtrip ship the original code and simply provide wrappers to fit their toolbox conventions. I assume that would also be the way to go for us. But let's discuss it.

**Comment by BenjaminBlankertz** [comment]
For including external function, we use so far the folder
  bbci_private/import
as I feel it would not be appropriate to include code of other people into our git. However, this requires that external users take care of themselves to get the respective functions and to include them into their Matlab path.

**Comment by venthur** [comment]
Legally, we could include certain libraries in our toolbox if their license is compatible with ours. Unfortunately we don't have decided on a license yet (see #2).

Generally speaking, code licensed under non-copyleft licenses like MIT, BSD and even the LGPL (note the leading L), can always be included. Projects licensed under a copyleft license like GPL can only be included if our project is licensed under the GPL as well.

**Comment by svendaehne** [comment]
Personally I would not have a problem with including code from others in our git. But I guess that is something we simply have to decide.

If we are going to include ICA code, then here are some options:
The fastICA code comes with GPL license and I found some SOBI (another ICA version) code that comes with BSD license. EEGLAB (and thus their ICA-Infomax implementation) comes with GPL as well. 

So I guess Basti is right, we need to decide for a license for our toolbox first, before we can thing about what to include -- if we include. ;-)

**Comment by svendaehne** [comment]
Some links, so we don't have to search again next time

http://research.ics.aalto.fi/ica/fastica/
http://www.mathworks.com/matlabcentral/fileexchange/32608-blind-modal-identification--bmid--toolbox/content/bmid_pkg/sobi.m
http://sccn.ucsd.edu/eeglab/

**Comment by svendaehne** [comment]
I separated the ICA wrapper issue from the PCA issue. PCA can be implemented by us. ICA has to be a wrapper for external code.
