### ISSUE TITLE
Part of fileutil_concatMatlab wrong. In which cases do we need that part?

### ISSUE THREAD

**Issue by MarkusWenzel** [bbci/bbci_public#63]
Do we need the following part of fileutil_concatMatlab at all?
Anyway, it seems to me to be outdated (old svn toolbox based on samples not on time).

if ~isempty(iMrkBV),
      if length(varargcat{iMrkBV})>1,
        orig_fs= file_loadMatlab(file_list{ii-1}, 'vars','fs_orig');
        TT(ii-1)= round(T(ii-1)/varargcat{iNfo}.fs*orig_fs);
        shift= sum(TT(1:ii-1));
        for ii= 1:length(varargcat{iMrkBV}),
          varargcat{iMrkBV}(ii).pos= varargcat{iMrkBV}(ii).pos + shift;
        end
        varargout{iMrkBV}= cat(1, varargout{iMrkBV}, varargcat{iMrkBV});
      else
        varargcat{iMrkBV}.pos= varargcat{iMrkBV}.pos + sum(T(1:ii-1));
        varargout{iMrkBV}= ...
            mrk_mergeMarkers(varargout{iMrkBV}, varargcat{iMrkBV});
      end
end

**Comment by BenjaminBlankertz** [comment]
This is for the case, that the markers are also stored in the 'original BrainVision format' (variable 'mrk_orig'). The times are stored in unit 'samples', can therefore require this code.
