### ISSUE TITLE
Variance channel rejection docu/implementation differences 

### ISSUE THREAD

**Issue by robintibor** [bbci/bbci_public#66]
Hi,
in https://github.com/bbci/bbci_public/blob/45cd9349dc60cb317e260b10d46de20bf9075afa/processing/utils/reject_varEventsAndChannels.m
the documentation doesn't seem to completely match what is happening I think(?)

From reading the code I thought the cleaning process is:
1. (Bandpass)
2. Epoch markers
3. Compute Variances
4. (Remove channels with too small variance)
5. Remove extreme outlier trials
6. (Remove channels with too high variance)
7. Main part, first always remove channels, then trials with too high variance (optionally multipass)
8. (Remove trials by relative variance (variance - mean variance across channels))
9. (Remove channels with highly varying (from trial to trial) variance)

In the documentation there is a point 6 before the main part which does not seem to exist?(https://bitbucket.org/robintibor/machine-learning-for-motor-imagery/src/d05718f585943691a8475bc315fe40cf85206d37/matlab/gold-standard/epo_reject_varEventsAndChannels.m?at=master#cl-37):

``` matlab
% (6) remove trails with a var > threshold, while (for opt.Whiskerperc = 10)
%       threshold = percentile(allVar, 90) + opt.Whiskerlength * diff(percentile(allVar, 10), percentile(allVar, 90))      
% (7) combined trials/channels rejection, optionally as multi-pass
```

Also, is it intended that there is an option `RemoveChannelsFirst` and in the main loop channels are also always cleaned first? 

Also, in the checks

``` matlab
 if sum(isout(:))>0.05*nEvents,
```

nEvents is always the original number of trials, not the number of "still good" trials.. is this intended? :)

**Comment by BenjaminBlankertz** [comment]
There was a bug in the documentation. Points (5) and (6) (referring to the help of the function, not the enumeration in the issue) described the same thing.
