### ISSUE TITLE
Add functionality of appending blockno within function proc_appendEpochs

### ISSUE THREAD

**Issue by MarkusWenzel** [bbci/bbci_public#69]

**Comment by BenjaminBlankertz** [comment]
Not sure, what you mean exactly. The 'blockno' should be a subfield of epo.event, and all subfields of epo.event should be taken into account by proc_appendEpochs. If not, that is a more general issue.

**Comment by MarkusWenzel** [comment]
Claimed

**Comment by MarkusWenzel** [comment]
Yes, 'blkno' is a subfield of epo.event and, in principle, all subfields of epo.event should be taken into account by proc_appendEpochs. However, each subfield requires special treatment. So for now, I add only epo.event.blkno.

**Comment by MarkusWenzel** [comment]
Needs to be column not row vector...

**Comment by MarkusWenzel** [comment]
Still open issue ... I will work on this later ...

**Comment by BenjaminBlankertz** [comment]
The proc_appendEpoch function is really in a bad state. I will complete rewrite it. Then we can test it together, ok?

**Comment by MarkusWenzel** [comment]
Ok.
