### ISSUE TITLE
implement classifier based on logistic regression

### ISSUE THREAD

**Issue by BenjaminBlankertz** [bbci/bbci_public#74]

**Comment by MihailBogojeski** [comment]
I could take this issue, since I already implemented a logistic regression classifier as the top level classifier for HLDA. I believe most of the code can be reused. Any specifics on the signatures?

**Comment by BenjaminBlankertz** [comment]
Yes, take it. That would be great. Signature should be the same as for other classifiers. If the function takes optional arguments. see train_SWLDAmatlab.m.

**Comment by svendaehne** [comment]
closed by merge #104
