### ISSUE TITLE
Spurious private directories

### ISSUE THREAD

**Issue by venthur** [bbci/bbci_public#84]
In the repository are a handful of directories named `private`:

``` sh
 $ find . -name private
./online/apply_functions/private
./validation/private
./fileio/private
./visualization/private
./visualization/utils/private
./processing/private
```

Is this intentional or should the contents be moved and the directories deleted?

**Comment by BenjaminBlankertz** [comment]
Directories called 'private' have a special meaning in Matlab. The functions contained in there are only accessible to functions of the parent directory.
So, it is intentional and the directories must not be deleted.
