### ISSUE TITLE
provide a wrapper for removal of EOG activity with regression

### ISSUE THREAD

**Issue by svendaehne** [bbci/bbci_public#9]
I have some code that "cleans" continous data from EOG activity, given a clear estimate of the EOG activity from the respective EOG channels (EOGh, EOGv channels, or F10 minus F9 etc). In order to make this accessable a wrapper function needs to be written.

**Comment by BenjaminBlankertz** [comment]
Mihail works on this one.

**Comment by svendaehne** [comment]
closed by merge #108
