### ISSUE TITLE
mrk_mergeMarkers.m is not merging subfield .y 

### ISSUE THREAD

**Issue by phoebe28** [bbci/bbci_public#98]
mrk_mergeMarkers.m has been changed recently and now is not working properly. The deleted code in the file seems it was moved to mrkutil_appendEventInfo.m, but this function is not updated then.

**Comment by MarkusWenzel** [comment]
Line 24 "mrk.y= cat(2, mrk1.y, mrk2.y);" will not work if the subfields .y of the two marker structures contain a different number of classes. E.g. one marker has one class, the second marker has two classes. 
On the other hand, the subfields .y will not be merged correctly if the two markers contain the same _number_ of classes, but not the same classes.
