### ISSUE TITLE
proc_spectrogram only works with arguments (data,freq) and freq defined

### ISSUE THREAD

**Issue by DanielMiklody** [bbci/bbci_public#99]
The function crashes, if the frequency is given as a single number (NoFreqBins) or if windowlength or windowoverlap is defined. This is contrary to the help given...
The problem is in line 125, where the reshape takes place (the matlab spectrogram function takes these values correclty, the help is taken from there).

The error is:

Error using reshape
To RESHAPE the number of elements must not change.
Error in proc_spectrogram (line 125)
  dat.x = reshape(S',[sz(1)+winlen-1  sz(2) nfreq]);

**Comment by BenjaminBlankertz** [comment]
Can you suggest a bug fix?

**Comment by DanielMiklody** [comment]
solved?!
